name: ⚠️ Alert
description: Test of an alert issue template
labels: ["⚠️ Alert"]
body:
  - type: markdown
    attributes:
      value: |
        > [!WARNING]  
        > If you want to report a bug for 1.0, please open it on the new repository.
  - type: input
    id: non-markdown-input
    attributes:
      label: Non-Markdown Input
